name: Download Docker Image

# 显式声明权限
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to download (e.g. ss93/tmhmm:latest)'
        required: true
        default: 'ss93/tmhmm:latest'
      tag:
        description: 'Tag for the release (e.g. v1.0)'
        required: true
        default: 'v1.0'

# ✅ 关键修复：添加 permissions
permissions:
  contents: write
  packages: read

jobs:
  download-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Parse image name
        id: parse
        run: |
          IMAGE_NAME=$(echo "${{ github.event.inputs.image }}" | sed 's/[:\/]/-/g')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Pull and save Docker image
        run: |
          docker pull ${{ github.event.inputs.image }}
          docker save ${{ github.event.inputs.image }} -o "${{ env.IMAGE_NAME }}.tar"
          ls -lh "${{ env.IMAGE_NAME }}.tar"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: ${{ env.IMAGE_NAME }}.tar
